apiVersion: v1
kind: Service
metadata:
  name: chatbot-svc
  namespace: chatbot
spec:
  selector:
    app: chatbot
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
  type: ClusterIP
